apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: astro-ai
resources:
  - ../../base
  - ingress.yaml
images:
  - name: astro-ai-api
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/astro-ai-api
    newTag: latest
